//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ART.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_ARTTYPE                     130
#define IDR_TOOLBAR1                    310
#define IDD_ARTTASKVIEW                 311
#define IDD_SEARCH                      312
#define IDD_SEARCH_IP                   313
#define IDC_HAND_CUR                    314
#define IDD_CONFIG_DEV                  315
#define IDD_DLG_CONFIG                  315
#define IDD_DLG_BASIC_PAGE              321
#define IDD_DLG_PORT_PAGE               322
#define IDB_CONFIG                      329
#define IDB_EXIT                        330
#define IDB_MONITOR                     331
#define IDB_PORTMAPP                    332
#define IDB_PORTMONITOR                 333
#define IDD_DLG_PORTPARA_CONFIG         339
#define IDD_SEARCH_IPRANGE              341
#define IDD_DLG_COM_CONSOLE             342
#define IDD_DLG_MONITOR                 343
#define IDD_DLG_CHANNELMODE_PAGE        345
#define IDD_DLG_PORT_CHANNEL            346
#define IDB_LOGO                        347
#define IDI_NETCONFIG                   348
#define IDB_BMP_LOGO                    349
#define IDI_ICON1                       355
#define IDI_ICON2                       356
#define IDB_SC5083                      357
#define IDC_STATIC_FUNC                 1000
#define IDC_STATIC_SEARCH_BY_IP         1001
#define IDC_STATIC_SEARCH               1002
#define IDC_STATIC_ADD                  1003
#define IDC_SEARCH_LIST                 1004
#define IDC_STATIC_SEARCH_BY_IP2        1004
#define IDC_STATIC_SEARCH_BY_IPRANGE    1004
#define IDC_BTN_STOP                    1005
#define IDC_SEARCHING_STATIC            1006
#define IDC_SEARCH_RESULT_STATIC        1007
#define IDC_EDIT1                       1007
#define IDC_DLG_DEV_TYPE                1008
#define IDC_EDIT2                       1008
#define IDC_EDIT_MSG                    1008
#define IDC_DLG_DEV_SYSNAME             1009
#define IDC_DLG_DEV_PORTNUM             1010
#define IDC_DLG_DEV_VERSION             1011
#define IDC_DLG_DEV_UPTIME              1012
#define IDC_TAB1                        1013
#define IDC_TAB_CONFIG                  1013
#define IDC_STATIC_DUMMY                1015
#define IDC_STATIC_BASIC                1016
#define IDC_STATIC_NETWORK              1017
#define IDC_STATIC_SYSNAME              1018
#define IDC_VAL_SYSNAME                 1019
#define IDC_STATIC_NETWORK2             1019
#define IDC_STATIC_TIME                 1020
#define IDC_VAL_DEVTIME                 1021
#define IDC_STATIC_TIME3                1021
#define IDC_STATIC_TIME2                1022
#define IDC_VAL_TIMEZONE                1023
#define IDC_STATIC_WEB_LABEL            1024
#define IDC_STATIC_TELNET_LABEL         1025
#define IDC_VAL_WEB_CONSOLE             1026
#define IDC_VAL_TELNET_CONSOLE          1027
#define IDC_STATIC_IP_ADDRESS           1028
#define IDC_STATIC_VAL_IPADDR           1029
#define IDC_STATIC_IP_ADDRESS3          1029
#define IDC_STATIC_IP_ADDRESS2          1030
#define IDC_STATIC_VAL_IPMASK           1031
#define IDC_EDIT_SYSNAME                1031
#define IDC_STATIC_IP_GATEWAY           1032
#define IDC_STATIC_VAL_IPMASK2          1033
#define IDC_STATIC_VAL_IPGATEWAY        1033
#define IDC_STATIC_IP_ADDRESS4          1033
#define IDC_EDIT_DEVTIME                1034
#define IDC_STATIC_IP_ADDRESS5          1034
#define IDC_COMBO_TIMEZONE              1035
#define IDC_RADIO_WEB1                  1036
#define IDC_STATIC_IP_ADDRESS6          1036
#define IDC_RADIO_WEB2                  1037
#define IDC_LIST_PORT1                  1037
#define IDC_STATIC_IP_GATEWAY2          1037
#define IDC_RADIO_TELNET1               1038
#define IDC_LIST_PORT2                  1038
#define IDC_RADIO_TELNET2               1039
#define IDC_BTN_PORTPARA                1039
#define IDC_EDIT_IPMASK                 1040
#define IDC_BTN_PORTMODE                1040
#define IDC_STATIC_COMPORT_SELECTED     1040
#define IDC_EDIT_IP                     1041
#define IDC_COMBO_BAUD_RATE             1041
#define IDC_EDIT_GATEWAY                1042
#define IDC_COMBO2                      1042
#define IDC_COMBO_PORT                  1042
#define IDC_COMBO_TCPSERVER_MAXCONN1    1042
#define IDC_COMBO_TCPSERVER_MAXCONN     1042
#define IDC_STATIC_PARITY               1043
#define IDC_COMBO_TCPSERVER_MAXCONN2    1043
#define IDC_COMBO_PARITY                1044
#define IDC_STATIC_PORT_SELECTED        1044
#define IDC_COMBO_TCPSERVER_MAXCONN3    1044
#define IDC_COMBO_DATA_BITES            1045
#define IDC_COMBO1                      1045
#define IDC_BTN_CONFIG_ALLPORT          1045
#define IDC_COMBO_DEVICE                1045
#define IDC_PORT_WORKMODE               1045
#define IDC_COMBO_STOP_BITS             1046
#define IDC_COMBO_TCPSERVER_MAXCONN4    1046
#define IDC_COMBO_INTERFACE             1047
#define IDC_EDIT_TCP_LISTENPORT         1047
#define IDC_EDIT_TCP_LISTENPORT1        1047
#define IDC_COMBO_TCPCONNECTION         1048
#define IDC_COMBO_FLOWCONTROL           1048
#define IDC_EDIT_TCP_LISTENPORT2        1048
#define IDC_STATIC_TCPSERVER_PORT       1049
#define IDC_STATIC_TCP_MAXCONNECTION    1050
#define IDC_EDIT_TCP_LISTENPORT3        1050
#define IDC_STATIC_DESTINATION_HOST     1051
#define IDC_STATIC_TCPCLIENT_HOST       1051
#define IDC_STATIC_HOST1                1052
#define IDC_EDIT_TCP_LISTENPORT4        1052
#define IDC_STATIC_HOST2                1053
#define IDC_EDIT_TCP_LISTENPORT5        1053
#define IDC_STATIC_HOST3                1054
#define IDC_EDIT_TCP_LISTENPORT6        1054
#define IDC_STATIC_HOST4                1055
#define IDC_COMBO_TCPSERVER_MAXCONN5    1055
#define IDC_EDIT_HOST1                  1056
#define IDC_EDIT_TCP_TARGET_HOST1       1056
#define IDC_EDIT_HOST2                  1057
#define IDC_COMBO_TCPSERVER_MAXCONN6    1057
#define IDC_EDIT_UDPCLIENT_HOST         1057
#define IDC_EDIT_HOST3                  1058
#define IDC_EDIT_TCP_TARGET_HOST2       1058
#define IDC_EDIT_HOST4                  1059
#define IDC_EDIT_TCP_TARGET_HOST3       1059
#define IDC_STATIC_DOT1                 1060
#define IDC_EDIT_TCP_TARGET_HOST4       1060
#define IDC_STATIC_DOT2                 1061
#define IDC_EDIT_TCP_TARGET_HOST5       1061
#define IDC_STATIC_DOT3                 1062
#define IDC_EDIT_TCP_TARGET_HOST6       1062
#define IDC_STATIC_DOT4                 1063
#define IDC_EDIT_HOST_PORT1             1064
#define IDC_EDIT_TARGET_HOST_PORT1      1064
#define IDC_EDIT_HOST_PORT2             1065
#define IDC_EDIT_TARGET_HOST_PORT2      1065
#define IDC_EDIT_UDPCLIENT_PORT         1065
#define IDC_EDIT_HOST_PORT3             1066
#define IDC_EDIT_TARGET_HOST_PORT3      1066
#define IDC_EDIT_HOST_PORT4             1067
#define IDC_EDIT_TARGET_HOST_PORT4      1067
#define IDC_STATIC_DESTINATION_PORT     1068
#define ID_STATIC_TCPCLIENT_PORT        1068
#define IDC_STATIC_TCPCLIENT_PORT       1068
#define IDC_STATIC_UDP_PORT             1069
#define IDC_EDIT4                       1070
#define IDC_EDIT_UDP_PORT               1070
#define IDC_STATIC_PORTSELECTED_PORTPARA 1071
#define IDC_EDIT_LOCAL_PORT             1071
#define IDC_EDIT_TARGET_HOST_PORT5      1071
#define IDC_STATIC_UDPCLIENT_PORT       1071
#define IDC_STATIC_PORTSELECTED_PORTMODE 1072
#define IDC_STATIC_DESTINATION_PORT2    1072
#define IDC_EDIT_TARGET_HOST_PORT6      1072
#define IDC_EDIT_LOCAL_PORT2            1073
#define IDC_BTN_REBOOT                  1073
#define IDC_EDIT_LOCAL_PORT3            1074
#define IDC_BTN_DEV_SAVEDATA            1074
#define IDC_EDIT_LOCAL_PORT4            1075
#define IDC_DATETIMEPICKER_DEVDATE      1076
#define IDC_EDIT_UDP_HOST1              1076
#define IDC_DATETIMEPICKER_DEVTIME      1077
#define IDC_EDIT_UDP_HOST2              1077
#define IDC_EDIT_UDP_HOSTPORT1          1078
#define IDC_STATIC_UDP_HOST1            1079
#define IDC_STATIC_UDP_HOST_START       1080
#define IDC_STATIC_UDP_HOST_END         1081
#define IDC_STATIC_UDP_HOST_PORT        1082
#define IDC_EDIT_UDP_HOST3              1083
#define IDC_EDIT_UDP_HOST4              1084
#define IDC_IPADDRESS1                  1085
#define IDC_EDIT_UDP_HOSTPORT2          1085
#define IDC_IPADDRESS2                  1086
#define IDC_GROUP_UDPHOST               1086
#define IDC_IPADDRESS3                  1087
#define IDC_STATIC_UDP_HOST2            1087
#define IDC_EDIT_UDP_HOST5              1088
#define IDC_IPADDRESS4                  1088
#define IDC_EDIT_UDP_HOST6              1089
#define IDC_IPADDRESS5                  1089
#define IDC_EDIT_UDP_HOSTPORT3          1090
#define IDC_IPADDRESS6                  1090
#define IDC_STATIC_UDP_HOST3            1091
#define IDC_EDIT_UDP_HOST7              1092
#define IDC_EDIT_UDP_HOST8              1093
#define IDC_EDIT_UDP_HOSTPORT4          1094
#define IDC_STATIC_UDP_HOST4            1095
#define IDC_GROUP_TCPCLIENT_HOSTLIST    1096
#define IDC_LIST_DEVICE                 1098
#define IDC_BTN_SEARCH                  1100
#define IDC_STATIC_SEARCH_RESULT        1103
#define IDC_IPADDRESS_IP_SEARCH         1104
#define IDC_RADIO1                      1105
#define IDC_RADIO2                      1106
#define IDC_CHECK1                      1107
#define IDC_CHECK_AUTOWRAP              1107
#define IDC_CHECK2                      1108
#define IDC_CHECK_SHOWSENDMSG           1108
#define IDC_CHECK3                      1109
#define IDC_CHECK_SHOWTIME              1109
#define IDC_BUTTON1                     1110
#define IDC_BTN_CLEAR                   1110
#define IDC_BTN_ADD_CHANNEL             1110
#define IDC_BTN_OK                      1110
#define IDC_EDIT3                       1111
#define IDC_EDIT_SENDMSG                1111
#define IDC_BTN_ADD_CHANNEL2            1111
#define IDC_BTN_DEL_CHANNEL             1111
#define IDC_BUTTON2                     1112
#define IDC_BTN_SEND                    1112
#define IDC_LIST1                       1113
#define IDC_BTN_CONNECT                 1114
#define IDC_GROUP_WORKMODE_PARAM        1115
#define IDC_STATIC_MONITOR_LABLE        1116
#define IDC_RADIO_PORTSWITCH            1117
#define IDC_RADIO_PORTSWITCH_ON         1117
#define IDC_RADIO_PORTSWITCH_OFF        1118
#define IDC_STATIC_TCPSERVER_MAXCONN    1119
#define IDC_STATIC_TCPSERVER_1          1120
#define IDC_STATIC_TCPSERVER_2          1121
#define IDC_STATIC_TCPSERVER_3          1122
#define IDC_STATIC_TCPSERVER_4          1123
#define IDC_STATIC_TCPSERVER_5          1124
#define IDC_STATIC_TCPSERVER_6          1125
#define IDC_STATIC_TCPSERVER_NO         1126
#define IDC_STATIC_TCPClient_No         1127
#define IDC_STATIC_UDPCLIENT_HOST       1127
#define IDC_STATIC_TCPCLIENT_1          1128
#define IDC_STATIC_TCPCLIENT_2          1129
#define IDC_STATIC_TABVIEW              1129
#define IDC_STATIC_TCPCLIENT_3          1130
#define IDC_STATIC_PORT_CHANNEL_NUM     1130
#define IDC_STATIC_TCPCLIENT_4          1131
#define IDC_EDIT_CHANNEL_NUM            1131
#define IDC_STATIC_TCPCLIENT_5          1132
#define IDC_RADIO_CHANNEL_ENABLE        1132
#define IDC_STATIC_TCPCLIENT_6          1133
#define IDC_RADIO_CHANNEL_DISABLE       1133
#define IDC_RADIO_CHANNEL_DISABLED      1133
#define IDC_STATIC_GROUP_CHANNEL        1134
#define IDC_STATIC_POS1                 1135
#define IDC_STATIC_POS2                 1136
#define IDC_STATIC_POS3                 1137
#define IDC_STATIC_POS4                 1138
#define IDC_IPADDRESS_TCPCLIENT_HOST    1139
#define IDC_IPADDRESS_UDPCLIENT_HOST    1140
#define IDC_PIC_PRODUCT                 1141
#define IDC_LIST_CHANNEL_STATIC         1142
#define IDC_NET1_MODE_STATIC            1143
#define IDC_NET1_DHCP                   1144
#define IDC_NET2_MODE_STATIC            1145
#define IDC_NET2_DHCP                   1146
#define IDC_STATIC_DEV_MODE             1147
#define ID_CONFIG                       32771
#define ID_MONITOR                      32772
#define ID_PORTMONITOR                  32773
#define ID_COMMAPING                    32774
#define ID_32775                        32775
#define ID_32777                        32777
#define ID_CONSOLE                      32778
#define ID_INDICATOR_TIME               59142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        358
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1148
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
